export const listData = [
    {
      id: 1,
      title: "Ford Fiesta 2018",
      brand: "Ford",
      img: "https://diego-sant.github.io/QuizApp/img/img279.svg",
      condition: "Usado",
      transmission: "Manual",
      buyOrRent: "Alugar",
      priceToRent: 120,
      fuel: "Flex",
      color: "Prata",
      address: "São Paulo, SP - Brasil",
      latitude: -23.59105941675351,
      longitude: -46.69087039560111,
    },
    {
        id: 2,
        title: "Chevrolet Onix 2020",
        brand: "Chevrolet",
        img: "https://diego-sant.github.io/QuizApp/img/img279.svg",
        condition: "Usado",
        transmission: "Automático",
        buyOrRent: "Alugar",
        priceToRent: 150,
        fuel: "Flex",
        color: "Vermelho",
        address: "Rio de Janeiro, RJ - Brasil",
        latitude: -23.016136893218345,
        longitude: -43.47166024220119,
    },
    {
        id: 3,
        title: "Toyota Corolla 2021",
        brand: "Toyota",
        img: "https://diego-sant.github.io/QuizApp/img/img279.svg",
        condition: "Usado",
        transmission: "Automático",
        buyOrRent: "Alugar",
        priceToRent: 200,
        fuel: "Gasolina",
        color: "Branco",
        address: "Brooklyn, NY - Estados Unidos",
        latitude: 40.65282902295364,
        longitude: -73.92201228321055,
    },
    {
        id: 4,
        title: "Chevrolet Cruze 2017",
        brand: "Chevrolet",
        img: "https://diego-sant.github.io/QuizApp/img/img279.svg",
        condition: "Usado",
        transmission: "Automático",
        buyOrRent: "Comprar",
        priceToBuy: 65.000,
        fuel: "Flex",
        color: "Preto",
        address: "Belo Horizonte, MG - Brasil",
        latitude: -19.951269448836708,
        longitude: -44.02706986808546,
    },
    {
        id: 5,
        title: "Toyota Hilux 2021",
        brand: "Toyota",
        img: "https://diego-sant.github.io/QuizApp/img/img279.svg",
        condition: "Novo",
        transmission: "Automático",
        buyOrRent: "Comprar",
        priceToBuy: 180.000,
        fuel: "Diesel",
        color: "Preto",
        address: "São Paulo, SP - Brasil",
        latitude: -23.59105941675351,
        longitude: -46.69087039560111,
    },
    {
        id: 6,
        title: "Honda Fit 2018",
        brand: "Honda",
        img: "https://diego-sant.github.io/QuizApp/img/img279.svg",
        condition: "Usado",
        transmission: "Automático",
        buyOrRent: "Comprar",
        priceToBuy: 75.000,
        fuel: "Flex",
        color: "Cinza",
        address: "Porto Alegre, RS - Brasil",
        latitude: -30.047071888163707,
        longitude: -51.197805952502364,
    },
]